### PR TITLE
MongoDB's url can be set via environment variable.

### PR DESCRIPTION
**Pull request by liwenqiu**
The purpose of this pull request is: i wanna deploy leanote using docker container tech.

I am going to run mongodb and leanote app in different container. The mongodb container expose 27017 port, and the leanote container will link to mongodb container. Mongodb's url will be injected into leanote container via environment variable.  so i hope that leanote app can get mongodb's url from environment variable.

Thx

### CODE REVIEW

**Comment by lealife** [comment]
Add "db.url=${MONGODB_URL}" on app.conf can solve your problem ?

**Comment by lealife** [comment]
You can config mongodb on app.conf

**Comment by liwenqiu** [comment]
Yes, below is simple example of Dockerfile

FROM golang:1.4.2
RUN go get github.com/revel/cmd/revel
RUN go get github.com/leanote/leanote
RUN revel build github.com/liwenqiu/leanote /opt/leanote
ENV mongodb_url=mongodb://mongodb:27017/leanote
ENTRYPOINT revel run github.com/leanote/leanote prod 9000
EXPOSE 9000
# EOF

you can see "ENV mongodb_url=mongodb://mongodb:27017/leanote", leanote can obtain URL.

After you merge to master, i will commit this Docker Image to hub.docker.com, then leanote will easy running via docker tech, and mongodb url can be amended outside docker container.

**Comment by lealife** [comment]
app.conf is not support ENV, so db.url=${MONGODB_URL} is not support.

**Comment by lealife** [comment]
"mongodb://mongodb:27017/leanote" is default mongodb configuration

**Comment by liwenqiu** [comment]
http://revel.github.io/manual/appconf.html

please ref to "Dynamic parameters" section, revel support read ENV first, null if no defined.

**Comment by lealife** [comment]
Thanks.
The "db.url" is just for more complex configuration. For env I add "db.urlEnv"

**Comment by ferstar** [comment]
add "db.urlEnv" cased a new issue: if the server host didn't set `MONGODB_URL` env, all connections to mongodb will be failed. here are the mongodb logs:
```
2015-09-09T15:12:56.871+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:43014 #2 (1 connection now open)
2015-09-09T15:12:56.872+0800 I QUERY    [conn2] assertion 13 not authorized for query on leanote.users ns:leanote.users query:{ Username: "admin" }
2015-09-09T15:12:56.872+0800 I QUERY    [conn2]  ntoskip:0 ntoreturn:-1
2015-09-09T15:12:57.053+0800 I QUERY    [conn2] assertion 13 not authorized for query on leanote.user_blogs ns:leanote.user_blogs query:{ SubDomain: "192" }
2015-09-09T15:12:57.054+0800 I QUERY    [conn2]  ntoskip:0 ntoreturn:-1
2015-09-09T15:12:57.054+0800 I QUERY    [conn2] assertion 13 not authorized for query on leanote.users ns:leanote.users query:{ Username: "admin" }
2015-09-09T15:12:57.054+0800 I QUERY    [conn2]  ntoskip:0 ntoreturn:-1
2015-09-09T15:12:57.054+0800 I QUERY    [conn2] assertion 13 not authorized for query on leanote.users ns:leanote.users query:{ Username: "" }
2015-09-09T15:12:57.054+0800 I QUERY    [conn2]  ntoskip:0 ntoreturn:-1
```

**Comment by lealife** [comment]
It seems that the Mongodb has started with auth

**Comment by ferstar** [comment]
是的, 数据库开启授权验证不是很合理的么?

**Comment by lealife** [comment]
如果你的数据库开了验证, 那MONGODB_URL是怎么设置的呢?

**Comment by lealife** [comment]
MONGODB_URL 应该设置类似: mongodb://root:root123@localhost:27017/leanote

**Comment by ferstar** [comment]
我是这样设置的
```shell
# mongdb
db.host=localhost
db.port=27017                                                                   
db.dbname=leanote # required
db.username=root # if not exists, please leave it blank
db.password=abc123 # if not exists, please leave it blank
# or you can set the mongdb url for more complex needs the format is:
# mongodb://myuser:mypass@localhost:40001,otherhost:40001/mydb
# db.url=mongodb://root:root123@localhost:27017/leanote
# db.urlEnv=${MONGODB_URL} # set url from env
```

**Comment by lealife** [comment]
这表示不能访问数据库, 请确认用户名密码是否能连接数据库

**Comment by ferstar** [comment]
用户名密码是正确的, 我只要把这行注释就可以用了
```
# db.urlEnv=${MONGODB_URL} # set url from env
```
所以

**Comment by lealife** [comment]
那不加urlEnv就行了? urlEnv 这个工作白加了!

**Pull request closed without merging**
